# Generated by Django 5.0.3 on 2024-04-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ballot_no', models.CharField(max_length=255)),
                ('voter_no', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
    ]
