# Generated by Django 5.0.3 on 2024-04-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('voteApp', '0003_votecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_1', models.BooleanField(default=False)),
                ('vote_2', models.BooleanField(default=False)),
                ('vote_1_candidates', models.CharField(max_length=255, null=True)),
                ('vote_2_candidates', models.CharField(max_length=255, null=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
