# Generated by Django 5.0.3 on 2024-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0004_votervote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votervote',
            name='voter',
            field=models.IntegerField(),
        ),
    ]
